# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Needy < Formula
  desc "AI Agent Coordination System using the Needs Pattern"
  homepage "https://github.com/akafred/needy"
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/akafred/needy/releases/download/v0.0.2/needy_darwin_amd64.tar.gz"
      sha256 "07a3858520640cd5e3e51f5c7245d0b55bb91775d64aca92e3fca84d866c0d11"

      def install
        bin.install "nd"
        bin.install "ndadm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/akafred/needy/releases/download/v0.0.2/needy_darwin_arm64.tar.gz"
      sha256 "7f5d2711c5f27c6e642304939701e833c6e5cae85ccf2ada992b523a18fe83e4"

      def install
        bin.install "nd"
        bin.install "ndadm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/akafred/needy/releases/download/v0.0.2/needy_linux_amd64.tar.gz"
      sha256 "120d2eac349909361f72f9e9d52d1b564f879a83a84c8ec54dca289ef60782c2"
      def install
        bin.install "nd"
        bin.install "ndadm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/akafred/needy/releases/download/v0.0.2/needy_linux_arm64.tar.gz"
      sha256 "a64c299881013c1c9b613798da8e433cd8ae8c95508cdcadfd689c378330e0c3"
      def install
        bin.install "nd"
        bin.install "ndadm"
      end
    end
  end
end
