# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Needy < Formula
  desc "AI Agent Coordination System using the Needs Pattern"
  homepage "https://github.com/akafred/needy"
  version "0.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/akafred/needy/releases/download/v0.0.4/needy_darwin_amd64.tar.gz"
      sha256 "8369c3d7d43f2facf91987d6127c12ae3122596c9ffe3d08258a336d5d7ed8fe"

      def install
        bin.install "nd"
        bin.install "ndadm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/akafred/needy/releases/download/v0.0.4/needy_darwin_arm64.tar.gz"
      sha256 "02dc2a456d080910ae8bf43372146d15398daf03d4a074621e8fa4a3f4507cca"

      def install
        bin.install "nd"
        bin.install "ndadm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/akafred/needy/releases/download/v0.0.4/needy_linux_amd64.tar.gz"
      sha256 "c1679b2c4b1bb21d4f72b349b2f94165110fafa120a1256e2edce15a4dae91ed"
      def install
        bin.install "nd"
        bin.install "ndadm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/akafred/needy/releases/download/v0.0.4/needy_linux_arm64.tar.gz"
      sha256 "bae0431b347622737d2ed294ba0423bb3e52b9b38829632dc19266a0a37f4862"
      def install
        bin.install "nd"
        bin.install "ndadm"
      end
    end
  end
end
