# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Needy < Formula
  desc "AI Agent Coordination System using the Needs Pattern"
  homepage "https://github.com/akafred/needy"
  version "0.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/akafred/needy/releases/download/v0.0.5/needy_darwin_amd64.tar.gz"
      sha256 "74a4714cb1c43fdd4f169db38cadf5b3003408bfc54f67d68f7087fe42ee8c6d"

      def install
        bin.install "nd"
        bin.install "ndadm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/akafred/needy/releases/download/v0.0.5/needy_darwin_arm64.tar.gz"
      sha256 "fbcb6e007734599797472d8ea4394a7667d413e7f5c6f2d9d2295706f5c27d29"

      def install
        bin.install "nd"
        bin.install "ndadm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/akafred/needy/releases/download/v0.0.5/needy_linux_amd64.tar.gz"
      sha256 "c5c2e1470335cc5b9537bd20a590e5ef312d984d55f7700b4c0d4cc1a450aa68"
      def install
        bin.install "nd"
        bin.install "ndadm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/akafred/needy/releases/download/v0.0.5/needy_linux_arm64.tar.gz"
      sha256 "5a357dd477fae07bd6406a1c5eed21f231f4a903b4acb5bd8b1dedc8ffc0c258"
      def install
        bin.install "nd"
        bin.install "ndadm"
      end
    end
  end
end
